Section "InputClass"
  Identifier "Apple touchpad"
  MatchProduct "bcm5974"
  Driver "libinput"
  Option "Tapping" "True"
  Option "NaturalScrolling" "True"
  Option "DisableWhileTyping" "True"
  Option "ClickMethod" "clickfinger"
EndSection
