pcm.card1 {
  type hw
  card 1
}
pcm.softvol {
  type softvol
  slave.pcm "card1"
  control.name "Master"
  control.card 1
  min_dB -51.0
  max_dB 0.0
}
pcm.!default {
  type plug
  slave.pcm "softvol"
}

