include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.2
PACKAGE_NAME = ScreenLock
APP_NAME = ScreenLock
ScreenLock_APPLICATION_ICON = ScreenLock.tiff


#
# Resource files
#
ScreenLock_RESOURCE_FILES = \
Resources/ScreenLock.tiff \
Resources/ScreenLock.help

#
# Header files
#
ScreenLock_HEADER_FILES = \
MyDelegate.h

#
# Objective-C Class files
#
ScreenLock_OBJC_FILES = \
MyDelegate.m

#
# Other sources
#
ScreenLock_OBJC_FILES += \
Main.m

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
