include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = Pass
APP_NAME = Pass
Pass_APPLICATION_ICON = pass.tiff 

#
# Resource files
#
Pass_RESOURCE_FILES = \
Resources/pass.tiff \
Resources/Pass.help 

#
# Header files
#
Pass_HEADER_FILES = \
MyDelegate.h \
Search.h \
ListController.h \
New.h

#
# Objective-C Class files
#
Pass_OBJC_FILES = \
MyDelegate.m \
Search.m \
ListController.m \
New.m

#
# Other sources
#
Pass_OBJC_FILES += \
Main.m

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
