#!/bin/bash

APPNAME=AgnostepManager
APPS_DIR=$(gnustep-config --variable=GNUSTEP_LOCAL_APPS)
LG=${LANG:0:2}
case "$LG" in
"fr")
TOOLS=Utilitaires;;
"en"|*)
TOOLS=Utilities;;
esac
RES=$APPS_DIR/$TOOLS/${APPNAME}.app/Resources

if [ ! -d $HOME/SOURCES/agnostep-desktop ];then
	stexec $RES/alert_missing.st
	TITLE="Recovering"
	APP=$APPS_DIR/$TOOLS/${APPNAME}.app/Recover
	xterm -T "${TITLE}" -e "$APP" &
else
	cd $HOME/SOURCES/agnostep-desktop
	APP=./agnostep.sh
	TITLE="AGNoStep Manager"
	xterm -T "${TITLE}" -e "$APP" &
fi

PID=$!
pidwait $PID
