#!/bin/bash

_PWD=`pwd`
APPNAME=AgnostepManager
APPS_DIR=$(gnustep-config --variable=GNUSTEP_LOCAL_APPS)
LG=${LANG:0:2}
case "$LG" in
"fr")
TOOLS=Utilitaires;;
"en"|*)
TOOLS=Utilities;;
esac
RES=$APPS_DIR/$TOOLS/${APPNAME}.app/Resources

function recovering
{
if [ ! -d $HOME/SOURCES ];then
	mkdir -p $HOME/SOURCES
	cd $HOME/SOURCES || exit 1
	git clone https://github.com/pcardona34/agnostep-desktop
fi
}

recovering
cd $_PWD
stexec $RES/alert_end.st
exit
