#!/bin/bash

##############################################################
### Discover a network printer
function info
{
printf "Note the URI below. You will need it to configure Common Unix Printing System (CUPS) later.\n"
sudo lpinfo --include-schemes dnssd -v
read -p "Type <Enter> to follow..." R
}

##############################################################
### web admin method to Set CUPS
function web
{
WEBB=`xdg-settings get default-web-browser`

if [ ! $? -eq 0 ];then
	printf "\nYou must install and set your default Web Browser.\n"
	exit 1
fi

xdg-open "http://localhost:631/printers/"
}

############################"

#info
web
