include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = UpMem
APP_NAME = UpMem
UpMem_APPLICATION_ICON = Memory.tiff


#
# Resource files
#
UpMem_RESOURCE_FILES = \
Resources/Memory.tiff

#
# Header files
#
UpMem_HEADER_FILES = \
MyDelegate.h \
Memory.h

#
# Objective-C Class files
#
UpMem_OBJC_FILES = \
MyDelegate.m \
Memory.m

#
# Other sources
#
UpMem_OBJC_FILES += \
Main.m

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
