#!/bin/bash

####################################################
### A G N o S t e p  -  Updater - by Patrick Cardona
### pcardona34 @ Github
###
### This is Free and Open Source software.
### Read License in the root directory.
####################################################

################################
### Updater
################################

################################
### VARS

if [ $# -eq 1 ];then
	ARG="$1"
else
	ARG="-h"
fi

PREFIX=$(echo ${LANG%.UTF-8} | awk -F'_' '{print $1}')
BELL=/usr/local/share/icons/bell.tif

###############################################
### Functions
###############################################
. /usr/local/bin/colors.sh

###################################################
### Update: check packages to update
###################################################

function update()
{
DELAY=10 # seconds

case $PREFIX in
	"fr")
	TITLE="Mise à jour du Système Debian"
	MSG="nouveaux paquets disponibles."
	OK="Votre système est à jour."
	ITEM1="Mettre à jour"
	ITEM2="Ne rien faire";;
	"en" | *)
	TITLE="Debian System Updater"
	MSG="new packages available."
	OK="Your Operating System is up to date."
	JOB="Installing new packages..."
	ITEM1="Do Upgrade"
	ITEM2="Do Nothing";;
esac

### Get info from Debian apt update
sleep $DELAY

### Updating the package list
sudo apt update &>/dev/null

### Search if upgradable packages exists
### We must substract one line of warning emitted by apt within a script
NB=$(( $(apt list --upgradable | wc -l) - 1 ))

### Uncomment the below two lines for debug purpose only
#echo "NUMBER: $NB"
#read -p "pause" R

if [ $NB -gt 0 ];then
	ANSWER=$(dunstify -u critical -i $BELL --action "UPGRADE","$ITEM1" --action "EXIT","$ITEM2" "$TITLE" "$NB $MSG")
	case "$ANSWER" in
		"2"|"EXIT") exit 0;;
		"UPGRADE")
			#pgrep Terminal
			#if [ $? -eq 1 ];then
			#	/System/Tools/openapp Terminal
			#fi
			#cd "$HOME" && exec $SHELL -c "Updater --upgrade";;
			cd $HOME && Updater --upgrade;;
	esac
else
	dunstify "$TITLE" "$OK"
fi
}
### End of update

#######################################
function upgrade()
{

case $PREFIX in
        "fr")
        TITLE="Mise à jour du Système Debian"
        MSG="Installation de nouveaux paquets..."
        OK="Votre système est à jour.";;
        "en" | *)
        TITLE="Debian System Updater"
        MSG="Installing new packages..."
        OK="Your Operating System is up to date.";;
esac

ID=$(dunstify "$TITLE" "$MSG" -t 0 -i $BELL -p)
sudo apt -y upgrade &>/dev/null && dunstify -C $ID
dunstify "$TITLE" "$OK" -i $BELL
}

### End of upgrade

#######################################
function myhelp()
{
#clear
printf "Updater Syntax:\n"
printf "$0 <OPTION>\n\n"
printf "Options:\n"
printf "\t--update | -d\t\tUpdate the Database of the packages.\n"
printf "\t--upgrade | -g\t\tUpgrade the Debian packages.\n"
printf "\t--help | -h\t\tPrint this help.\n\n"
}
### End of help

######################################
### main script

case "$ARG" in
	"--update"|"-d")
	update;;
	"--upgrade"|"-g")
	upgrade;;
	"*")
	myhelp;;
esac
