#!/bin/bash

APP=nano
APPNAME=Nano

if [ $# -eq 2 ] ; then
	ARG="$2"
	TITLE="$APPNAME - $ARG"
else
	ARG=""
   	TITLE="$APPNAME"
fi

APPDIR=$(gnustep-config --variable=GNUSTEP_LOCAL_APPS)
LG=${LANG:0:2}
case "$LG" in
"fr") TOOLS=Utilitaires;;
"en") TOOLS=Utilities;;
esac
RES=$APPDIR/$TOOLS/${APPNAME}.app/Resources

pgrep --count Nano
if [ $? -gt 1 ];then
	stexec $RES/alert.st
	exit 1
else
	xterm -name "$TITLE" -e "transset -a --dec 0.05 && $APP $ARG $date_today"
fi
