#!/bin/bash

APP=nano

if [ $# -eq 2 ] ; then
	ARG="$2"
	TITLE="$APP - $ARG"
else
	ARG=""
   TITLE="$APP"
fi

PID=$(pgrep nano)
if [ $? -eq 0 ];then
	stexec Resources/alert.st
	exit 1
else
	xterm -T "${TITLE}" -e "transset -a --dec 0.05 && $APP $ARG $date_today"
fi


