include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.2
PACKAGE_NAME = OpenDisk
APP_NAME = OpenDisk
OpenDisk_APPLICATION_ICON = OpenDisk.tiff


#
# Resource files
#
OpenDisk_RESOURCE_FILES = \
Resources/OpenDisk.tiff \
Resources/OpenDisk.help

#
# Header files
#
OpenDisk_HEADER_FILES = \
MyDelegate.h

#
# Objective-C Class files
#
OpenDisk_OBJC_FILES = \
MyDelegate.m

#
# Other sources
#
OpenDisk_OBJC_FILES += \
Main.m

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
