include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.2
PACKAGE_NAME = AgnostepManager
APP_NAME = AgnostepManager
AgnostepManager_APPLICATION_ICON = AgnostepManager.tiff


#
# Resource files
#
AgnostepManager_RESOURCE_FILES = \
Resources/AgnostepManager.tiff \
Resources/AgnostepManager.help

#
# Header files
#
AgnostepManager_HEADER_FILES = \
MyDelegate.h

#
# Objective-C Class files
#
AgnostepManager_OBJC_FILES = \
MyDelegate.m

#
# Other sources
#
AgnostepManager_OBJC_FILES += \
Main.m

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
