include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.2
PACKAGE_NAME = Printer
APP_NAME = Printer
Printer_APPLICATION_ICON = Printer.tiff


#
# Resource files
#
Printer_RESOURCE_FILES = \
Resources/Printer.tiff \
Resources/Printer.help

#
# Header files
#
Printer_HEADER_FILES = \
MyDelegate.h

#
# Objective-C Class files
#
Printer_OBJC_FILES = \
MyDelegate.m

#
# Other sources
#
Printer_OBJC_FILES += \
Main.m

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
