####################################################
### A G N o S t e p  -  Desktop - by Patrick Cardona
### (c) 2026 - pcardona34 @ Github
###
### Thanks for the GNUstep Developers Community
### This is Free and Open Source software.
### Read License in the root directory.
####################################################

####################################################
### TestCuckoo: a little app to test sound...
### GNUMakefile
####################################################


include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = TestCuckoo
TestCuckoo_APPLICATION_ICON = TestCuckoo.tiff

TestCuckoo_RESOURCE_FILES = \
Resources \
Resources/TestCuckoo.tiff \
Resources/cuckoo.wav \
Resources/Info-gnustep.plist

TestCuckoo_HEADER_FILES = \
Delegate.h

TestCuckoo_OBJC_FILES = \
Delegate.m \
Main.m

include $(GNUSTEP_MAKEFILES)/application.make
