include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = Updater
APP_NAME = Updater
Updater_APPLICATION_ICON = Upgrade.tiff 


#
# Resource files
#
Updater_RESOURCE_FILES = \
Resources/Upgrade.tiff

#
# Header files
#
Updater_HEADER_FILES = \
MyDelegate.h \
ListController.h \
ProgressController.h

#
# Objective-C Class files
#
Updater_OBJC_FILES = \
MyDelegate.m \
ListController.m \
ProgressController.m

#
# Other sources
#
Updater_OBJC_FILES += \
Main.m

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
